<a href="https://colab.research.google.com/github/manasuii/Machine-Learning-Fundamentals/blob/main/PytorchFUN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [4]:
a=torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(2,3)

tensor([[0.6883, 0.5679, 0.7137],
        [0.5920, 0.0943, 0.8963]])

In [20]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
print("using arrange ->",torch.arange(0,10,2))
print("using linspace ->",torch.linspace(0,10,10))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [24]:
print("using eye-->",torch.eye(5))

using eye--> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [25]:
print("uing full -->",torch.full((3,3),5))

uing full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [26]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(x)

tensor([[         1091296379,          4294967296, 7310224140986744832],
        [                113,          1092018768,          1092023504]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [33]:
x.dtype

torch.int64

Tensor Data Types


In [34]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [37]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [39]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [40]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [41]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [42]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

Element wise operation


In [45]:
a=torch.ones(2,3)
b=torch.ones(2,3)
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [46]:
a+b

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [47]:
c=torch.tensor([1,-2,3,-4])

In [48]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [49]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [50]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [51]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [53]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [54]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [55]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction Operation


In [56]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [59]:
torch.sum(e)


tensor(24.)

In [61]:

torch.sum(e,dim=1)

tensor([15.,  9.])

In [60]:
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [62]:
torch.mean(e)
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [63]:
torch.median(e)

tensor(0.)

In [64]:
torch.prod(e)

tensor(0.)

In [65]:
torch.var(e)

tensor(19.6000)

Matrix OPerations

In [66]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [67]:
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [68]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
torch.dot(vector1,vector2)

tensor(11)

In [71]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [74]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[7., 8., 3.],
        [6., 1., 5.],
        [5., 0., 4.]])

In [75]:
torch.det(h)

tensor(21.0000)

In [76]:
torch.inverse(h)

tensor([[ 0.1905, -1.5238,  1.7619],
        [ 0.0476,  0.6190, -0.8095],
        [-0.2381,  1.9048, -1.9524]])

Comparison Operations

In [77]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[3, 8, 8],
        [3, 3, 5]])
tensor([[0, 6, 4],
        [0, 8, 4]])


In [78]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

Special Functions

In [79]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[7., 2., 3.],
        [8., 5., 6.]])

In [80]:
torch.log(k)

tensor([[1.9459, 0.6931, 1.0986],
        [2.0794, 1.6094, 1.7918]])

In [81]:
torch.exp(k)

tensor([[1096.6332,    7.3891,   20.0855],
        [2980.9580,  148.4132,  403.4288]])

In [82]:
torch.sqrt(k)

tensor([[2.6458, 1.4142, 1.7321],
        [2.8284, 2.2361, 2.4495]])

In [84]:
torch.sigmoid(k)

tensor([[0.9991, 0.8808, 0.9526],
        [0.9997, 0.9933, 0.9975]])

In [87]:
torch.softmax(k,dim=0)

tensor([[0.2689, 0.0474, 0.0474],
        [0.7311, 0.9526, 0.9526]])

In [88]:
torch.relu(k)

tensor([[7., 2., 3.],
        [8., 5., 6.]])

In [89]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])
tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])


In [90]:
m.add_(n)

tensor([[1.0939, 0.1762, 1.3909],
        [0.5098, 1.1259, 0.9638]])

In [91]:
m


tensor([[1.0939, 0.1762, 1.3909],
        [0.5098, 1.1259, 0.9638]])

In [92]:
n

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])