<a href="https://colab.research.google.com/github/manasuii/Machine-Learning-Fundamentals/blob/main/Pytorch_NNmodule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [6]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,x):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out


In [7]:
#create dataset
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.5954],
        [0.5649],
        [0.6293],
        [0.6564],
        [0.5554],
        [0.6335],
        [0.6380],
        [0.6641],
        [0.6620],
        [0.6730]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.bias

Parameter containing:
tensor([0.1998], requires_grad=True)

In [11]:
!pip install torchinfo

In [12]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [21]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,x):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out


In [22]:
#create dataset
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.4320],
        [0.4415],
        [0.4300],
        [0.4303],
        [0.4330],
        [0.4417],
        [0.4374],
        [0.4318],
        [0.4359],
        [0.4314]], grad_fn=<SigmoidBackward0>)

In [23]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,x):
    out=self.network(features)


    return out


In [24]:
#create dataset
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.5058],
        [0.4897],
        [0.4845],
        [0.5172],
        [0.4922],
        [0.4895],
        [0.4736],
        [0.4931],
        [0.4791],
        [0.5070]], grad_fn=<SigmoidBackward0>)