<a href="https://colab.research.google.com/github/manasuii/AI-ML_Fundamentals/blob/main/Pytorch_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

12/28/2025:Day 1:Manasi Thapa

In [ ]:
import torch

In [ ]:
a=torch.empty(2,3)

In [ ]:
a

tensor([[6.7697e-04, 7.1449e+31, 6.3276e+22],
        [4.7429e+30, 3.5852e-09, 1.4013e-44]])

In [ ]:
a=torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a=torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.7872, 0.4925, 0.1325],
        [0.8564, 0.4572, 0.1651]])

In [ ]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

Scalar operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2205, 0.9128],
        [0.0713, 0.3129]])

In [ ]:
#addition
x + 2
#substraction
x - 2
#multiplication
x * 3
#division
x / 3
#int division
(x * 100)//3
#mod
((x * 100)//3)%2
#power
x**2

tensor([[0.0486, 0.8332],
        [0.0051, 0.0979]])

In [ ]:
torch.neg(x)

tensor([[-0.2205, -0.9128],
        [-0.0713, -0.3129]])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 1., 6.],
        [5., 4., 1.]])

In [ ]:

torch.sum(e)
#columns
torch.sum(e, dim=0)
#rows
torch.sum(e, dim=1)

tensor([ 8., 10.])

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 2, 9],
        [8, 9, 5]])
tensor([[6, 9],
        [1, 8],
        [4, 4]])


In [ ]:
torch.matmul(f, g)

tensor([[ 74, 106],
        [ 77, 164]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])


torch.dot(vector1, vector2)

tensor(11)

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 5., 0.],
        [1., 1., 7.],
        [2., 7., 2.]])

In [ ]:
torch.det(h)

tensor(-222.)

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 9., 2.],
        [7., 4., 4.]])

In [ ]:
torch.log(k)

tensor([[1.0986, 2.1972, 0.6931],
        [1.9459, 1.3863, 1.3863]])

In [ ]:
torch.exp(k)

tensor([[2.0086e+01, 8.1031e+03, 7.3891e+00],
        [1.0966e+03, 5.4598e+01, 5.4598e+01]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.8808],
        [0.9991, 0.9820, 0.9820]])

In [ ]:
torch.softmax(k, dim=0)

tensor([[0.0180, 0.9933, 0.1192],
        [0.9820, 0.0067, 0.8808]])

In [ ]:
torch.relu(k)

tensor([[3., 9., 2.],
        [7., 4., 4.]])

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1929, 0.6077, 0.1747],
        [0.2509, 0.5238, 0.8919]])
tensor([[0.0294, 0.0639, 0.3210],
        [0.8356, 0.4934, 0.3805]])


In [ ]:
m.add_(n)

tensor([[0.2223, 0.6716, 0.4957],
        [1.0864, 1.0173, 1.2724]])

Autograd

In [ ]:
x=torch.tensor(3.0,requires_grad=True)


In [ ]:
y=x**2

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
a=torch.tensor(4.0,requires_grad=True)



In [ ]:
b=a**2

In [ ]:
c=torch.sin(b)

In [ ]:
c.backward()

In [ ]:
a.grad

tensor(-7.6613)

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [ ]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

Clearing Autograd

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
x.grad.zero_()

tensor(0.)

NN Module

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,x):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out


In [ ]:
#create dataset
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.4560],
        [0.4460],
        [0.4441],
        [0.4551],
        [0.4891],
        [0.4400],
        [0.4067],
        [0.4381],
        [0.4705],
        [0.4608]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2650], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,x):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out


In [ ]:

features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.5410],
        [0.5347],
        [0.5312],
        [0.5403],
        [0.5338],
        [0.5334],
        [0.5350],
        [0.5375],
        [0.5390],
        [0.5293]], grad_fn=<SigmoidBackward0>)

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,x):
    out=self.network(features)


    return out


In [ ]:
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)


tensor([[0.6195],
        [0.6250],
        [0.6396],
        [0.6064],
        [0.6175],
        [0.6161],
        [0.6154],
        [0.6097],
        [0.6080],
        [0.6415]], grad_fn=<SigmoidBackward0>)

Optimizers

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)
x = torch.randn(100, 1)
y = 2*x + 1


In [ ]:
model_sgd = SimpleNN()
criterion = nn.MSELoss()
optimizer_sgd = optim.SGD(model_sgd.parameters(), lr=0.01)

for epoch in range(100):
    y_pred = model_sgd(x)
    loss = criterion(y_pred, y)

    optimizer_sgd.zero_grad()
    loss.backward()
    optimizer_sgd.step()

    if epoch % 20 == 0:
        print(f"SGD Epoch {epoch}, Loss: {loss.item():.4f}")

SGD Epoch 0, Loss: 6.3860
SGD Epoch 20, Loss: 2.6884
SGD Epoch 40, Loss: 1.1318
SGD Epoch 60, Loss: 0.4765
SGD Epoch 80, Loss: 0.2006


In [ ]:
model_adam = SimpleNN()
criterion = nn.MSELoss()
optimizer_adam = optim.Adam(model_adam.parameters(), lr=0.01)

for epoch in range(100):
    y_pred = model_adam(x)
    loss = criterion(y_pred, y)

    optimizer_adam.zero_grad()
    loss.backward()
    optimizer_adam.step()

    if epoch % 20 == 0:
        print(f"Adam Epoch {epoch}, Loss: {loss.item():.4f}")


Adam Epoch 0, Loss: 4.2995
Adam Epoch 20, Loss: 3.2703
Adam Epoch 40, Loss: 2.4459
Adam Epoch 60, Loss: 1.8147
Adam Epoch 80, Loss: 1.3399


Datasets and DataLoader

In [ ]:
from sklearn.datasets import make_classification
import torch

 firstly,i created a synthetic classification data set using sklearn

In [ ]:

X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X.shape

(10, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
y.shape

(10,)

In [ ]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [ ]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
